node:
	install multi_sw_hs.xinetd /etc/xinetd.d/multi_sw_hs
	install multi_sw_hs multi_sw_hs.py /usr/local/bin/
	service xinetd stop; service xinetd start

main:
	install multi_sw_hs_test multi_sw_hs_main /usr/local/bin/
