#!/bin/sh

#MACS_MAX=100
#PROC_MAX=2
MACS_MAX=100000
PROC_MAX=10

SW=11
IF=eth1
IP=10.10.20.129
MAC=0
MACS=100

rm -f /tmp/multi_sw_hs_test.*

killall /opt/nox/bin/nox_core
kill `ps ax | grep /usr/local/bin/multi_sw_hs_test | awk '{print $1}'` > /dev/null 2>&1

rm -f /root/mac_stat /root/thread_stat

echo 0 0 > /root/mac_stat
cd /opt/nox/bin/; /opt/nox/bin/nox_core --libdir=/opt/nox/lib -i ptcp:6633 -v -v --threads=10 switchqos > /tmp/nox_core.log 2>&1 &

while ! tail -1 /root/mac_stat
do
	sleep 1
done

mac=$MAC
while [ `tail -1 /root/mac_stat | awk '{print $2}'` -le $MACS_MAX ]
do
	for i in `seq $PROC_MAX`
	do
		mac=$(($mac+$MACS))
		/usr/local/bin/multi_sw_hs_test $SW $IF $IP $mac $MACS $i &
		sleep 1
	done
done
